--<ScriptOptions statementTerminator=";"/>

CREATE SCHEMA "Client";

CREATE TABLE "Client"."ACCOUNT_TYPE" (
		"ACCOUNT_TYPE_ID" CHAR(5) NOT NULL,
		"ACCOUNT_TYPE" CHAR(5) NULL,
		"TYPE_DESCRIPTION" CHAR(5) NULL,
		"ACCOUNT_ID" CHAR(5) NOT NULL,
		"ACCOUNT_TYPE_ID1" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."ADDRESS" (
		"ADDRESS_ID" CHAR(5) NOT NULL,
		"FIRST_LINE" CHAR(5) NULL,
		"CITY" CHAR(5) NULL,
		"POSTAL_CODE" CHAR(5) NULL
	);

CREATE TABLE "Client"."CAMPAIGN" (
		"CAMPAIGN_ID" CHAR(5) NOT NULL,
		"CAMPAIGN_NAME" CHAR(5) NULL,
		"CAMPAIGN_DETAILS" CHAR(5) NULL,
		"ADDRESS_ID" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."CAMPAIGN_MEMBER" (
		"MEMBER_ID" CHAR(5) NOT NULL,
		"MEMBER_NAME" CHAR(5) NULL,
		"DOB" CHAR(5) NULL,
		"GENDER" CHAR(5) NULL,
		"ADDRESS_ID" CHAR(5) NULL,
		"CAMPAIGN_ID" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."CLIENT_ACCOUNT" (
		"ACCOUNT_TYPE_ID1" CHAR(5) NOT NULL,
		"ACCOUNT_ID" CHAR(5) NOT NULL,
		"ACCOUNT_TYPE_ID" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."CONTACT_INFORMATION" (
		"CONTACT_ID" CHAR(5) NOT NULL,
		"CONTACT_TYPE" CHAR(5) NULL,
		"EMAIL_ADDRESS" CHAR(5) NULL,
		"MOBILE_NUMBER" CHAR(5) NULL
	);

CREATE TABLE "Client"."ENTITY1" (
	);

CREATE TABLE "Client"."MEMBER_LEAD" (
		"MEMBER_ID" CHAR(5) NOT NULL,
		"PRODUCT_ID" CHAR(5) NOT NULL,
		"CONTACT_ID" CHAR(5) NOT NULL,
		"ORG_ID" CHAR(5) NOT NULL,
		"DETAILS" CHAR(5) NULL
	);

CREATE TABLE "Client"."ORDER" (
		"ORDER_ID" CHAR(5) NOT NULL,
		"ORDER_DETAILS" CHAR(5) NULL,
		"PRODUCT_ID" CHAR(5) NOT NULL,
		"ACCOUNT_ID" CHAR(5) NOT NULL,
		"QUOTATION_ID" CHAR(5) NULL,
		"ACCOUNT_TYPE_ID1" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."ORGANIZATION" (
		"ORG_ID" CHAR(5) NOT NULL,
		"ORGANIZATION_NAME" CHAR(5) NULL,
		"ORGANIZATION_TYPE" CHAR(5) NULL,
		"DETAILS" CHAR(5) NULL
	);

CREATE TABLE "Client"."ORGANIZATION_ADDRESS" (
		"ORG_ID" CHAR(5) NOT NULL,
		"ADDRESS_ID" CHAR(5) NOT NULL
	);

CREATE TABLE "Client"."PRODUCT" (
		"PRODUCT_ID" CHAR(5) NOT NULL,
		"PRODUCT_NAME" CHAR(5) NULL,
		"PRODUCT_TYPE" CHAR(5) NULL,
		"PRODUCT_DESCRIPTION" CHAR(5) NULL
	);

CREATE TABLE "Client"."QUOTATION" (
		"QUOTATION_ID" CHAR(5) NOT NULL,
		"DETAILS" CHAR(5) NULL
	);

ALTER TABLE "Client"."ACCOUNT_TYPE" ADD CONSTRAINT "ACCOUNT_TYPE_PK" PRIMARY KEY CLUSTERED
	("ACCOUNT_TYPE_ID");

ALTER TABLE "Client"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY CLUSTERED
	("ADDRESS_ID");

ALTER TABLE "Client"."CAMPAIGN" ADD CONSTRAINT "CAMPAIGN_PK" PRIMARY KEY CLUSTERED
	("CAMPAIGN_ID");

ALTER TABLE "Client"."CAMPAIGN_MEMBER" ADD CONSTRAINT "CAMPAIGN_MEMBER_PK" PRIMARY KEY CLUSTERED
	("MEMBER_ID");

ALTER TABLE "Client"."CLIENT_ACCOUNT" ADD CONSTRAINT "CLIENT_ACCOUNT_PK" PRIMARY KEY CLUSTERED
	("ACCOUNT_TYPE_ID1",
	 "ACCOUNT_ID");

ALTER TABLE "Client"."CONTACT_INFORMATION" ADD CONSTRAINT "CONTACT_INFORMATION_PK" PRIMARY KEY CLUSTERED
	("CONTACT_ID");

ALTER TABLE "Client"."MEMBER_LEAD" ADD CONSTRAINT "MEMBER_LEAD_PK" PRIMARY KEY CLUSTERED
	("MEMBER_ID",
	 "PRODUCT_ID",
	 "CONTACT_ID",
	 "ORG_ID");

ALTER TABLE "Client"."ORDER" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY CLUSTERED
	("ORDER_ID");

ALTER TABLE "Client"."ORGANIZATION" ADD CONSTRAINT "ORGANIZATION_PK" PRIMARY KEY CLUSTERED
	("ORG_ID");

ALTER TABLE "Client"."ORGANIZATION_ADDRESS" ADD CONSTRAINT "ORGANIZATION_ADDRESS_PK" PRIMARY KEY CLUSTERED
	("ORG_ID",
	 "ADDRESS_ID");

ALTER TABLE "Client"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY CLUSTERED
	("PRODUCT_ID");

ALTER TABLE "Client"."QUOTATION" ADD CONSTRAINT "QUOTATION_PK" PRIMARY KEY CLUSTERED
	("QUOTATION_ID");

ALTER TABLE "Client"."ACCOUNT_TYPE" ADD CONSTRAINT "ACCOUNT_TYPE_CLIENT_ACCOUNT_FK" FOREIGN KEY
	("ACCOUNT_TYPE_ID1",
	 "ACCOUNT_ID")
	REFERENCES "Client"."CLIENT_ACCOUNT"
	("ACCOUNT_TYPE_ID1",
	 "ACCOUNT_ID");

ALTER TABLE "Client"."CAMPAIGN" ADD CONSTRAINT "CAMPAIGN_ADDRESS_FK" FOREIGN KEY
	("ADDRESS_ID")
	REFERENCES "Client"."ADDRESS"
	("ADDRESS_ID");

ALTER TABLE "Client"."CAMPAIGN_MEMBER" ADD CONSTRAINT "CAMPAIGN_MEMBER_ADDRESS_FK" FOREIGN KEY
	("ADDRESS_ID")
	REFERENCES "Client"."ADDRESS"
	("ADDRESS_ID");

ALTER TABLE "Client"."CAMPAIGN_MEMBER" ADD CONSTRAINT "CAMPAIGN_MEMBER_CAMPAIGN_FK" FOREIGN KEY
	("CAMPAIGN_ID")
	REFERENCES "Client"."CAMPAIGN"
	("CAMPAIGN_ID");

ALTER TABLE "Client"."CLIENT_ACCOUNT" ADD CONSTRAINT "CLIENT_ACCOUNT_ACCOUNT_TYPE_FK" FOREIGN KEY
	("ACCOUNT_TYPE_ID")
	REFERENCES "Client"."ACCOUNT_TYPE"
	("ACCOUNT_TYPE_ID");

ALTER TABLE "Client"."CLIENT_ACCOUNT" ADD CONSTRAINT "CLIENT_ACCOUNT_ACCOUNT_TYPE_FK1" FOREIGN KEY
	("ACCOUNT_TYPE_ID1")
	REFERENCES "Client"."ACCOUNT_TYPE"
	("ACCOUNT_TYPE_ID");

ALTER TABLE "Client"."MEMBER_LEAD" ADD CONSTRAINT "MEMBER_LEAD_CAMPAIGN_MEMBER_FK" FOREIGN KEY
	("MEMBER_ID")
	REFERENCES "Client"."CAMPAIGN_MEMBER"
	("MEMBER_ID");

ALTER TABLE "Client"."MEMBER_LEAD" ADD CONSTRAINT "MEMBER_LEAD_CONTACT_INFORMATION_FK" FOREIGN KEY
	("CONTACT_ID")
	REFERENCES "Client"."CONTACT_INFORMATION"
	("CONTACT_ID");

ALTER TABLE "Client"."MEMBER_LEAD" ADD CONSTRAINT "MEMBER_LEAD_ORGANIZATION_FK" FOREIGN KEY
	("ORG_ID")
	REFERENCES "Client"."ORGANIZATION"
	("ORG_ID");

ALTER TABLE "Client"."MEMBER_LEAD" ADD CONSTRAINT "MEMBER_LEAD_PRODUCT_FK" FOREIGN KEY
	("PRODUCT_ID")
	REFERENCES "Client"."PRODUCT"
	("PRODUCT_ID");

ALTER TABLE "Client"."ORDER" ADD CONSTRAINT "ORDER_CLIENT_ACCOUNT_FK" FOREIGN KEY
	("ACCOUNT_TYPE_ID1",
	 "ACCOUNT_ID")
	REFERENCES "Client"."CLIENT_ACCOUNT"
	("ACCOUNT_TYPE_ID1",
	 "ACCOUNT_ID");

ALTER TABLE "Client"."ORDER" ADD CONSTRAINT "ORDER_PRODUCT_FK" FOREIGN KEY
	("PRODUCT_ID")
	REFERENCES "Client"."PRODUCT"
	("PRODUCT_ID");

ALTER TABLE "Client"."ORDER" ADD CONSTRAINT "ORDER_QUOTATION_FK" FOREIGN KEY
	("QUOTATION_ID")
	REFERENCES "Client"."QUOTATION"
	("QUOTATION_ID");

ALTER TABLE "Client"."ORGANIZATION_ADDRESS" ADD CONSTRAINT "ORGANIZATION_ADDRESS_ADDRESS_FK" FOREIGN KEY
	("ADDRESS_ID")
	REFERENCES "Client"."ADDRESS"
	("ADDRESS_ID");

ALTER TABLE "Client"."ORGANIZATION_ADDRESS" ADD CONSTRAINT "ORGANIZATION_ADDRESS_ORGANIZATION_FK" FOREIGN KEY
	("ORG_ID")
	REFERENCES "Client"."ORGANIZATION"
	("ORG_ID");

