--<ScriptOptions statementTerminator=";"/>

CREATE TABLE Schema.ACCOUNT_TYPE (
		ACCOUNT_TYPE_ID CHAR(5) NOT NULL, 
		ACCOUNT_TYPE CHAR(5), 
		TYPE_DESCRIPTION CHAR(5), 
		ACCOUNT_ID CHAR(5) NOT NULL, 
		ACCOUNT_TYPE_ID1 CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.ADDRESS (
		ADDRESS_ID CHAR(5) NOT NULL, 
		FIRST_LINE CHAR(5), 
		CITY CHAR(5), 
		POSTAL_CODE CHAR(5)
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.CAMPAIGN (
		CAMPAIGN_ID CHAR(5) NOT NULL, 
		CAMPAIGN_NAME CHAR(5), 
		CAMPAIGN_DETAILS CHAR(5), 
		ADDRESS_ID CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.CAMPAIGN_MEMBER (
		MEMBER_ID CHAR(5) NOT NULL, 
		MEMBER_NAME CHAR(5), 
		DOB CHAR(5), 
		GENDER CHAR(5), 
		ADDRESS_ID CHAR(5), 
		CAMPAIGN_ID CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.CLIENT_ACCOUNT (
		ACCOUNT_TYPE_ID1 CHAR(5) NOT NULL, 
		ACCOUNT_ID CHAR(5) NOT NULL, 
		ACCOUNT_TYPE_ID CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.CONTACT_INFORMATION (
		CONTACT_ID CHAR(5) NOT NULL, 
		CONTACT_TYPE CHAR(5), 
		EMAIL_ADDRESS CHAR(5), 
		MOBILE_NUMBER CHAR(5)
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.ENTITY1 (
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.MEMBER_LEAD (
		MEMBER_ID CHAR(5) NOT NULL, 
		PRODUCT_ID CHAR(5) NOT NULL, 
		CONTACT_ID CHAR(5) NOT NULL, 
		ORG_ID CHAR(5) NOT NULL, 
		DETAILS CHAR(5)
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.ORDER (
		ORDER_ID CHAR(5) NOT NULL, 
		ORDER_DETAILS CHAR(5), 
		PRODUCT_ID CHAR(5) NOT NULL, 
		ACCOUNT_ID CHAR(5) NOT NULL, 
		QUOTATION_ID CHAR(5), 
		ACCOUNT_TYPE_ID1 CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.ORGANIZATION (
		ORG_ID CHAR(5) NOT NULL, 
		ORGANIZATION_NAME CHAR(5), 
		ORGANIZATION_TYPE CHAR(5), 
		DETAILS CHAR(5)
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.ORGANIZATION_ADDRESS (
		ORG_ID CHAR(5) NOT NULL, 
		ADDRESS_ID CHAR(5) NOT NULL
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.PRODUCT (
		PRODUCT_ID CHAR(5) NOT NULL, 
		PRODUCT_NAME CHAR(5), 
		PRODUCT_TYPE CHAR(5), 
		PRODUCT_DESCRIPTION CHAR(5)
	)
	DATA CAPTURE NONE;

CREATE TABLE Schema.QUOTATION (
		QUOTATION_ID CHAR(5) NOT NULL, 
		DETAILS CHAR(5)
	)
	DATA CAPTURE NONE;

ALTER TABLE Schema.ACCOUNT_TYPE ADD CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY
	(ACCOUNT_TYPE_ID);

ALTER TABLE Schema.ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY
	(ADDRESS_ID);

ALTER TABLE Schema.CAMPAIGN ADD CONSTRAINT CAMPAIGN_PK PRIMARY KEY
	(CAMPAIGN_ID);

ALTER TABLE Schema.CAMPAIGN_MEMBER ADD CONSTRAINT CAMPAIGN_MEMBER_PK PRIMARY KEY
	(MEMBER_ID);

ALTER TABLE Schema.CLIENT_ACCOUNT ADD CONSTRAINT CLIENT_ACCOUNT_PK PRIMARY KEY
	(ACCOUNT_TYPE_ID1, 
	 ACCOUNT_ID);

ALTER TABLE Schema.CONTACT_INFORMATION ADD CONSTRAINT CONTACT_INFORM_PK PRIMARY KEY
	(CONTACT_ID);

ALTER TABLE Schema.MEMBER_LEAD ADD CONSTRAINT MEMBER_LEAD_PK PRIMARY KEY
	(MEMBER_ID, 
	 PRODUCT_ID, 
	 CONTACT_ID, 
	 ORG_ID);

ALTER TABLE Schema.ORDER ADD CONSTRAINT ORDER_PK PRIMARY KEY
	(ORDER_ID);

ALTER TABLE Schema.ORGANIZATION ADD CONSTRAINT ORGANIZATION_PK PRIMARY KEY
	(ORG_ID);

ALTER TABLE Schema.ORGANIZATION_ADDRESS ADD CONSTRAINT ORGANIZATION_A_PK PRIMARY KEY
	(ORG_ID, 
	 ADDRESS_ID);

ALTER TABLE Schema.PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY
	(PRODUCT_ID);

ALTER TABLE Schema.QUOTATION ADD CONSTRAINT QUOTATION_PK PRIMARY KEY
	(QUOTATION_ID);

ALTER TABLE Schema.ACCOUNT_TYPE ADD CONSTRAINT __FK3 FOREIGN KEY
	(ACCOUNT_TYPE_ID1, 
	 ACCOUNT_ID)
	REFERENCES Schema.CLIENT_ACCOUNT
	(ACCOUNT_TYPE_ID1, 
	 ACCOUNT_ID);

ALTER TABLE Schema.CAMPAIGN ADD CONSTRAINT __FK6 FOREIGN KEY
	(ADDRESS_ID)
	REFERENCES Schema.ADDRESS
	(ADDRESS_ID);

ALTER TABLE Schema.CAMPAIGN_MEMBER ADD CONSTRAINT __FK7 FOREIGN KEY
	(CAMPAIGN_ID)
	REFERENCES Schema.CAMPAIGN
	(CAMPAIGN_ID);

ALTER TABLE Schema.CAMPAIGN_MEMBER ADD CONSTRAINT __FK8 FOREIGN KEY
	(ADDRESS_ID)
	REFERENCES Schema.ADDRESS
	(ADDRESS_ID);

ALTER TABLE Schema.CLIENT_ACCOUNT ADD CONSTRAINT __FK4 FOREIGN KEY
	(ACCOUNT_TYPE_ID)
	REFERENCES Schema.ACCOUNT_TYPE
	(ACCOUNT_TYPE_ID);

ALTER TABLE Schema.CLIENT_ACCOUNT ADD CONSTRAINT __FK5 FOREIGN KEY
	(ACCOUNT_TYPE_ID1)
	REFERENCES Schema.ACCOUNT_TYPE
	(ACCOUNT_TYPE_ID);

ALTER TABLE Schema.MEMBER_LEAD ADD CONSTRAINT __FK10 FOREIGN KEY
	(MEMBER_ID)
	REFERENCES Schema.CAMPAIGN_MEMBER
	(MEMBER_ID);

ALTER TABLE Schema.MEMBER_LEAD ADD CONSTRAINT __FK11 FOREIGN KEY
	(ORG_ID)
	REFERENCES Schema.ORGANIZATION
	(ORG_ID);

ALTER TABLE Schema.MEMBER_LEAD ADD CONSTRAINT __FK12 FOREIGN KEY
	(PRODUCT_ID)
	REFERENCES Schema.PRODUCT
	(PRODUCT_ID);

ALTER TABLE Schema.MEMBER_LEAD ADD CONSTRAINT __FK9 FOREIGN KEY
	(CONTACT_ID)
	REFERENCES Schema.CONTACT_INFORMATION
	(CONTACT_ID);

ALTER TABLE Schema.ORDER ADD CONSTRAINT ORDER_PRODUCT_FK FOREIGN KEY
	(PRODUCT_ID)
	REFERENCES Schema.PRODUCT
	(PRODUCT_ID);

ALTER TABLE Schema.ORDER ADD CONSTRAINT ORDER_QUOTATION_FK FOREIGN KEY
	(QUOTATION_ID)
	REFERENCES Schema.QUOTATION
	(QUOTATION_ID);

ALTER TABLE Schema.ORDER ADD CONSTRAINT __FK2 FOREIGN KEY
	(ACCOUNT_TYPE_ID1, 
	 ACCOUNT_ID)
	REFERENCES Schema.CLIENT_ACCOUNT
	(ACCOUNT_TYPE_ID1, 
	 ACCOUNT_ID);

ALTER TABLE Schema.ORGANIZATION_ADDRESS ADD CONSTRAINT __FK FOREIGN KEY
	(ADDRESS_ID)
	REFERENCES Schema.ADDRESS
	(ADDRESS_ID);

ALTER TABLE Schema.ORGANIZATION_ADDRESS ADD CONSTRAINT __FK13 FOREIGN KEY
	(ORG_ID)
	REFERENCES Schema.ORGANIZATION
	(ORG_ID);

