--<ScriptOptions statementTerminator=";"/>

CREATE TABLE Schema.ACCOUNT (
		ACCOUNT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTNUMBER VARCHAR(32672), 
		ACCOUNTSOURCE VARCHAR(32672), 
		ACCOUNT_CLASSIFICATION__C VARCHAR(32672), 
		ACCOUNT_STATUS_SUMMARY__C VARCHAR(32672), 
		ACTIVE_MSA__C CHAR(1), 
		ANCESTORS__C VARCHAR(32672), 
		ANNUALREVENUE INTEGER, 
		BSIMEMBERSHIPEXPIRYDATE__C DATE, 
		BSIMEMBERSHIPNO__C VARCHAR(32672), 
		BSI_MEMBER__C CHAR(1), 
		BILLINGCITY VARCHAR(32672), 
		BILLINGCOUNTRY VARCHAR(32672), 
		BILLINGGEOCODEACCURACY VARCHAR(32672), 
		BILLINGLATITUDE INTEGER, 
		BILLINGLONGITUDE INTEGER, 
		BILLINGPOSTALCODE VARCHAR(32672), 
		BILLINGSTATE VARCHAR(32672), 
		BILLINGSTREET VARCHAR(32672), 
		BRANCH_NUMBER__C VARCHAR(32672), 
		CI_ACCOUNT__C VARCHAR(20), 
		COI_RISK__C CHAR(1), 
		CERTIFYINGORGANISATIONS__C VARCHAR(32672), 
		CHANNELPROGRAMLEVELNAME VARCHAR(32672), 
		CHANNELPROGRAMNAME VARCHAR(32672), 
		CHARITYREGNO__C VARCHAR(32672), 
		CLIENT_ENGAGEMENT_MANAGER__C VARCHAR(20), 
		COREGNO__C VARCHAR(32672), 
		CODICE_FISCALE__C VARCHAR(32672), 
		COMMERCIAL_COMPANY_NAME__C VARCHAR(32672), 
		COMPANYLOGO__C VARCHAR(32672), 
		COMPANY_TYPE__C VARCHAR(32672), 
		COMPETITOR_TYPE__C VARCHAR(32672), 
		CONTACTLEVEL__C VARCHAR(32672), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		CREDIT_CHECK_COMPLETION__C CHAR(1), 
		CURRENCYISOCODE VARCHAR(32672), 
		CURRENT_STATUS__C VARCHAR(32672), 
		DNBOPTIMIZER__DNB_D_U_N_S_NUMBER__C VARCHAR(32672), 
		DNBOPTIMIZER__DNBCOMPANYRECORD__C VARCHAR(20), 
		DUNS_NUMBER__C VARCHAR(32672), 
		D_B_CONFIDENCE_CODE__C VARCHAR(32672), 
		D_B_ID_LINKED_TO_SALESFORCE_ACCOUNT__C VARCHAR(32672), 
		DEFAULT_SITE__C VARCHAR(20), 
		DESCRIPTION VARCHAR(32672), 
		DETAILSEXISTINGREG__C VARCHAR(32672), 
		DOMESTIC_ULTIMATE_DUNS__C VARCHAR(32672), 
		ENTROPY_ACCOUNT_TAG__C VARCHAR(32672), 
		ENTROPY_ACTIVATION_DATE__C DATE, 
		ENTROPY_ADD_ONS__C VARCHAR(32672), 
		ENTROPY_CLIENT_REQUESTS__C VARCHAR(32672), 
		ENTROPY_DEACTIVATION_DATE__C DATE, 
		ENTROPY_EXEC_SPONSOR__C VARCHAR(20), 
		ENTROPY_LICENSE_TYPE__C VARCHAR(32672), 
		ENTROPY_MODULE__C VARCHAR(32672), 
		ENTROPY_TOTAL_SITES_LICENCED__C INTEGER, 
		ENTROPY_VERSION__C VARCHAR(32672), 
		EXISTINGREGISTRATIONS__C CHAR(1), 
		EXISTING_CLIENT__C VARCHAR(32672), 
		EXISTING_REGISTRATION_EXPIRY_DATE__C DATE, 
		FAX VARCHAR(32672), 
		FUNDING_BODY__C VARCHAR(32672), 
		GLOBALSALESFORCEID__C VARCHAR(32672), 
		GLOBAL_ULTIMATE_DUNS__C VARCHAR(32672), 
		GOLDENCOMPANYID__C INTEGER, 
		GOLDEN_ID__C VARCHAR(32672), 
		HQ_PARENT_DUNS__C VARCHAR(32672), 
		HOSTED__C VARCHAR(32672), 
		HOWMANYSITESARETHEREALTOGETHER__C INTEGER, 
		INDUSTRY VARCHAR(32672), 
		INDUSTRY_SECONDARY__C VARCHAR(32672), 
		INSOLVENT__C CHAR(1), 
		INVOICE_RECIPIENT_CODE__C VARCHAR(32672), 
		ISCUSTOMERPORTAL CHAR(1), 
		ISDELETED CHAR(1), 
		ISMASTER__C CHAR(1), 
		ISPARTNER CHAR(1), 
		JIGSAW VARCHAR(32672), 
		JIGSAWCOMPANYID VARCHAR(32672), 
		KEYACCOUNT__C CHAR(1), 
		KEY_BSI_OPPORTUNITY__C VARCHAR(32672), 
		KEY_BSI_STRENGTH__C VARCHAR(32672), 
		KEY_BSI_THREAT__C VARCHAR(32672), 
		KEY_BSI_VISION_HELP__C VARCHAR(32672), 
		KEY_BSI_VISION_SUMMARY__C VARCHAR(32672), 
		KEY_BSI_WEAKNESS__C VARCHAR(32672), 
		KEY_CLIENT_OP_OBJECTIVES_HELP__C VARCHAR(32672), 
		KEY_CLIENT_OP_OBJECTIVES_SUMMARY__C VARCHAR(32672), 
		KEY_CLIENT_OPPORTUNITY__C VARCHAR(32672), 
		KEY_CLIENT_ORG_OBJECTIVES_HELP__C VARCHAR(32672), 
		KEY_CLIENT_ORG_OBJECTIVES_SUMMARY__C VARCHAR(32672), 
		KEY_CLIENT_STRENGTH__C VARCHAR(32672), 
		KEY_CLIENT_THREAT__C VARCHAR(32672), 
		KEY_CLIENT_WEAKNESS__C VARCHAR(32672), 
		LID__LINKEDIN_COMPANY_ID__C VARCHAR(32672), 
		LASTACTIVITYDATE DATE, 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		LASTREFERENCEDDATE TIMESTAMP, 
		LASTVIEWEDDATE TIMESTAMP, 
		LOCAL_CITY__C VARCHAR(32672), 
		LOCAL_CITY_C__C VARCHAR(32672), 
		LOCAL_COUNTRY__C VARCHAR(32672), 
		LOCAL_POST_CODE__C VARCHAR(32672), 
		LOCAL_STATE__C VARCHAR(32672), 
		LOCAL_STREET__C VARCHAR(32672), 
		MSA_LOGO__C VARCHAR(32672), 
		MSA_PRICEBOOK__C VARCHAR(20), 
		MANAGED_ACCOUNT__C CHAR(1), 
		MASTERRECORDID VARCHAR(20), 
		MATCH_GRADE__C VARCHAR(32672), 
		NAME VARCHAR(32672), 
		NAMELOCAL VARCHAR(32672), 
		NON_STANDARDS_TERMS_AND_CONDITIONS__C CHAR(1), 
		NUMBEROFEMPLOYEES INTEGER, 
		NUMBER_OF_COUNTRIES__C INTEGER, 
		NUMBER_OF_SITES_CONFIGURED__C INTEGER, 
		ORGTYPE1__C VARCHAR(32672), 
		ORGTYPE3__C VARCHAR(32672), 
		ORGTYPE2__C VARCHAR(32672), 
		OTHERCERTIFYINGORGANISATIONS__C VARCHAR(32672), 
		OTHER_APPLICATIONS__C VARCHAR(32672), 
		OWNERID VARCHAR(20), 
		OWNERSHIP VARCHAR(32672), 
		PS_EXTERNAL_ID__C VARCHAR(32672), 
		PARENTID VARCHAR(20), 
		PATCHASSIGNMENT__C VARCHAR(32672), 
		PHONE VARCHAR(32672), 
		PHOTOURL VARCHAR(32672), 
		POSTCODEAREA__C VARCHAR(32672), 
		POTENTIAL_CONFLICT_OF_INTEREST__C CHAR(1), 
		PREPAYMENT__C CHAR(1), 
		RATING VARCHAR(32672), 
		RECORDTYPEID VARCHAR(20), 
		REFERENCE_NUMBER__C VARCHAR(32672), 
		REFERENCEABLE__C VARCHAR(32672), 
		REGISTERED_EMAIL_FOR_INVOICE__C VARCHAR(32672), 
		SAP2SFDC__C INTEGER, 
		SAP_CLIENT_REFERENCE_NUMBER__C VARCHAR(32672), 
		SCS_ACCOUNT_CSA__C VARCHAR(32672), 
		SCS_ADVISORS__C VARCHAR(32672), 
		SCS_BDM_ASSIGNED_OWNER__C VARCHAR(32672), 
		SCS_MARKETING_ACCOUNT_TAG__C VARCHAR(32672), 
		SCS_PRODUCTS__C VARCHAR(32672), 
		SQL_VERSION__C VARCHAR(32672), 
		SHIPPINGCITY VARCHAR(32672), 
		SHIPPINGCOUNTRY VARCHAR(32672), 
		SHIPPINGGEOCODEACCURACY VARCHAR(32672), 
		SHIPPINGLATITUDE INTEGER, 
		SHIPPINGLONGITUDE INTEGER, 
		SHIPPINGPOSTALCODE VARCHAR(32672), 
		SHIPPINGSTATE VARCHAR(32672), 
		SHIPPINGSTREET VARCHAR(32672), 
		SIC VARCHAR(32672), 
		SICDESC VARCHAR(32672), 
		SITE VARCHAR(32672), 
		SITENUMBER__C INTEGER, 
		SPECIAL_INSTRUCTIONS__C VARCHAR(32672), 
		SPECIALLBILLINGNOTES__C VARCHAR(32672), 
		STANDARDS_CODES_HELD__C VARCHAR(32672), 
		SYSTEMMODSTAMP TIMESTAMP, 
		TCODEDESCR__C VARCHAR(32672), 
		TCODEFULL__C VARCHAR(32672), 
		TCODEPREFIX__C VARCHAR(32672), 
		TARGET_ACCOUNT__C CHAR(1), 
		TERRITORY__C VARCHAR(20), 
		TICKERSYMBOL VARCHAR(32672), 
		TRADING_CITY__C VARCHAR(32672), 
		TRADING_COUNTRY__C VARCHAR(32672), 
		TRADING_POST_CODE__C VARCHAR(32672), 
		TRADING_STATE__C VARCHAR(32672), 
		TRADING_STREET__C VARCHAR(32672), 
		TRADING_NAME__C VARCHAR(32672), 
		TYPE VARCHAR(32672), 
		TYPEICON__C VARCHAR(32672), 
		ULTIMATE_PARENT_REFERENCE_DATA__C VARCHAR(32672), 
		ULTIMATE_PARENT__C VARCHAR(32672), 
		VAT_NUMBER_NONEU__C VARCHAR(32672), 
		VAT_NUMBER__C VARCHAR(32672), 
		VAT_TAX_DETAILS__C VARCHAR(32672), 
		WEBSITE VARCHAR(32672), 
		WHATTYPEOFSITE__C VARCHAR(32672), 
		WINDOWS_SERVER_VERSION__C VARCHAR(32672), 
		X18_DIGIT_ACCOUNT_ID__C VARCHAR(32672), 
		ISELL__OSKEYID__C VARCHAR(32672), 
		OF_OPPS__C INTEGER
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTBRAND (
		ACCOUNTBRAND_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTID VARCHAR(20), 
		CITY VARCHAR(32672), 
		COMPANYNAME VARCHAR(32672), 
		COUNTRY VARCHAR(32672), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		CURRENCYISOCODE VARCHAR(32672), 
		EMAIL VARCHAR(32672), 
		GEOCODEACCURACY VARCHAR(32672), 
		ISDELETED CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		LASTREFERENCEDDATE TIMESTAMP, 
		LASTVIEWEDDATE TIMESTAMP, 
		LATITUDE INTEGER, 
		LOGOID VARCHAR(20), 
		LOGOURL VARCHAR(32672), 
		LONGITUDE INTEGER, 
		NAME VARCHAR(32672), 
		OWNERID VARCHAR(20), 
		PHONE VARCHAR(32672), 
		POSTALCODE VARCHAR(32672), 
		STATE VARCHAR(32672), 
		STREET VARCHAR(32672), 
		SYSTEMMODSTAMP TIMESTAMP, 
		WEBSITE VARCHAR(32672)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTBRANDSHARE (
		ACCOUNTBRANDSHARE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCESSLEVEL VARCHAR(32672), 
		ISDELETED CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		PARENTID VARCHAR(20), 
		ROWCAUSE VARCHAR(32672), 
		USERORGROUPID VARCHAR(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTCONTACTROLE (
		ACCOUNTCONTACTROLE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTID VARCHAR(20), 
		CONTACTID VARCHAR(20), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		ISDELETED CHAR(1), 
		ISPRIMARY CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		ROLE VARCHAR(32672), 
		SYSTEMMODSTAMP TIMESTAMP
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTFEED (
		ACCOUNTFEED_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		BESTCOMMENTID VARCHAR(20), 
		BODY VARCHAR(32672), 
		COMMENTCOUNT INTEGER, 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		INSERTEDBYID VARCHAR(20), 
		ISDELETED CHAR(1), 
		ISRICHTEXT CHAR(1), 
		LASTMODIFIEDDATE TIMESTAMP, 
		LIKECOUNT INTEGER, 
		LINKURL VARCHAR(32672), 
		NETWORKSCOPE VARCHAR(32672), 
		PARENTID VARCHAR(20), 
		RELATEDRECORDID VARCHAR(20), 
		SYSTEMMODSTAMP TIMESTAMP, 
		TITLE VARCHAR(32672), 
		TYPE VARCHAR(32672), 
		VISIBILITY VARCHAR(32672)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTHISTORY (
		ACCOUNTHISTORY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTID VARCHAR(20), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		DATATYPE VARCHAR(32672), 
		FIELD VARCHAR(32672), 
		ISDELETED CHAR(1)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTPARTNER (
		ACCOUNTPARTNER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTFROMID VARCHAR(20), 
		ACCOUNTTOID VARCHAR(20), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		ISDELETED CHAR(1), 
		ISPRIMARY CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		OPPORTUNITYID VARCHAR(20), 
		REVERSEPARTNERID VARCHAR(20), 
		ROLE VARCHAR(32672), 
		SYSTEMMODSTAMP TIMESTAMP
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTSHARE (
		ACCOUNTSHARE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTACCESSLEVEL VARCHAR(32672), 
		ACCOUNTID VARCHAR(20), 
		CASEACCESSLEVEL VARCHAR(32672), 
		CONTACTACCESSLEVEL VARCHAR(32672), 
		ISDELETED CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		OPPORTUNITYACCESSLEVEL VARCHAR(32672), 
		ROWCAUSE VARCHAR(32672), 
		USERORGROUPID VARCHAR(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE Schema.ACCOUNTTEAMMEMBER (
		ACCOUNTTEAMMEMBER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		ACCOUNTACCESSLEVEL VARCHAR(32672), 
		ACCOUNTID VARCHAR(20), 
		CASEACCESSLEVEL VARCHAR(32672), 
		CONTACTACCESSLEVEL VARCHAR(32672), 
		CREATEDBYID VARCHAR(20), 
		CREATEDDATE TIMESTAMP, 
		CURRENCYISOCODE VARCHAR(32672), 
		ISDELETED CHAR(1), 
		LASTMODIFIEDBYID VARCHAR(20), 
		LASTMODIFIEDDATE TIMESTAMP, 
		OPPORTUNITYACCESSLEVEL VARCHAR(32672), 
		PHOTOURL VARCHAR(32672), 
		SYSTEMMODSTAMP TIMESTAMP, 
		TEAMMEMBERROLE VARCHAR(32672), 
		TITLE VARCHAR(32672), 
		USERID VARCHAR(20)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE Schema.ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY
	(ACCOUNT_ID);

ALTER TABLE Schema.ACCOUNTBRAND ADD CONSTRAINT ACCOUNTBRAND_PK PRIMARY KEY
	(ACCOUNTBRAND_ID);

ALTER TABLE Schema.ACCOUNTBRANDSHARE ADD CONSTRAINT ACCOUNTBRANDSHARE_PK PRIMARY KEY
	(ACCOUNTBRANDSHARE_ID);

ALTER TABLE Schema.ACCOUNTCONTACTROLE ADD CONSTRAINT ACCOUNTCONTACTROLE_PK PRIMARY KEY
	(ACCOUNTCONTACTROLE_ID);

ALTER TABLE Schema.ACCOUNTFEED ADD CONSTRAINT ACCOUNTFEED_PK PRIMARY KEY
	(ACCOUNTFEED_ID);

ALTER TABLE Schema.ACCOUNTHISTORY ADD CONSTRAINT ACCOUNTHISTORY_PK PRIMARY KEY
	(ACCOUNTHISTORY_ID);

ALTER TABLE Schema.ACCOUNTPARTNER ADD CONSTRAINT ACCOUNTPARTNER_PK PRIMARY KEY
	(ACCOUNTPARTNER_ID);

ALTER TABLE Schema.ACCOUNTSHARE ADD CONSTRAINT ACCOUNTSHARE_PK PRIMARY KEY
	(ACCOUNTSHARE_ID);

ALTER TABLE Schema.ACCOUNTTEAMMEMBER ADD CONSTRAINT ACCOUNTTEAMMEMBER_PK PRIMARY KEY
	(ACCOUNTTEAMMEMBER_ID);

ALTER TABLE Schema.ACCOUNT ADD CONSTRAINT ACCOUNT_ACCOUNT_FK FOREIGN KEY
	(ACCOUNT_ID)
	REFERENCES Schema.ACCOUNT
	(ACCOUNT_ID);

ALTER TABLE Schema.ACCOUNT ADD CONSTRAINT ACCOUNT_ACCOUNT_FK1 FOREIGN KEY
	(ACCOUNT_ID)
	REFERENCES Schema.ACCOUNT
	(ACCOUNT_ID);

